import { transformSFC } from '@xui/compiler'

export interface MiniAppConfig {
  pages: string[]
  window?: {
    backgroundTextStyle?: string
    navigationBarBackgroundColor?: string
    navigationBarTitleText?: string
    navigationBarTextStyle?: string
  }
  tabBar?: {
    color?: string
    selectedColor?: string
    backgroundColor?: string
    list: Array<{
      pagePath: string
      text: string
      iconPath?: string
      selectedIconPath?: string
    }>
  }
  subpackages?: Array<{
    root: string
    pages: string[]
  }>
}

export interface MiniPageConfig {
  usingComponents?: Record<string, string>
  navigationBarTitleText?: string
  navigationBarBackgroundColor?: string
  enablePullDownRefresh?: boolean
  onReachBottomDistance?: number
}

export function transformTemplateToWxml(template: string): string {
  let wxml = template

  wxml = wxml.replace(/@click="([^"]+)"/g, 'bindtap="$1"')
  wxml = wxml.replace(/@input="([^"]+)"/g, 'bindinput="$1"')
  wxml = wxml.replace(/@change="([^"]+)"/g, 'bindchange="$1"')
  wxml = wxml.replace(/@([a-zA-Z-]+)="([^"]+)"/g, 'bind$1="$2"')

  wxml = wxml.replace(/:([^:=]+)="([^"]+)"/g, '$1="{{$2}}"')

  wxml = wxml.replace(/v-for="([^"]+)"/g, (_match, expr) => {
    const itemMatch = expr.match(/^(\w+)\s+in\s+(\w+)$/)
    if (itemMatch) {
      return `wx:for="{{${itemMatch[2]}}}" wx:for-item="${itemMatch[1]}" wx:key="${itemMatch[1]}.id || index"`
    }
    return `wx:for="{{${expr}}}" wx:key="index"`
  })

  wxml = wxml.replace(/v-if="([^"]+)"/g, 'wx:if="{{$1}}"')
  wxml = wxml.replace(/v-else-if="([^"]+)"/g, 'wx:elif="{{$1}}"')
  wxml = wxml.replace(/v-else/g, 'wx:else')
  wxml = wxml.replace(/v-show="([^"]+)"/g, 'wx:if="{{$1}}"')

  wxml = wxml.replace(/v-model="([^"]+)"/g, 'value="{{' + '$1' + '}}" bindinput="__handleInput"')

  return `<!-- Generated by XUI -->\n${wxml}`
}

export function transformStylesToWxss(styles: string, unitRatio = 2): string {
  let wxss = styles
  wxss = wxss.replace(/(\d+)px/g, (_match, value) => `${parseInt(value) * unitRatio}rpx`)
  return `/* Generated by XUI */\n${wxss}`
}

export function generatePageJs(pageName: string): string {
  return `Page({
  data: {},
  onLoad(options) {
    console.log('${pageName} loaded')
  }
})`
}

export function generatePageJson(pageName: string, config?: MiniPageConfig): string {
  return JSON.stringify({
    usingComponents: {},
    navigationBarTitleText: pageName,
    ...config,
  }, null, 2)
}

export function generateAppJs(config: MiniAppConfig): string {
  return `App({
  onLaunch() {
    console.log('XUI Mini App launched')
  },
  onShow() {
    console.log('XUI Mini App showed')
  },
  onHide() {
    console.log('XUI Mini App hidden')
  }
})`
}

export function generateAppJson(config: MiniAppConfig): string {
  return JSON.stringify({
    pages: config.pages,
    window: config.window || {
      navigationBarTitleText: 'XUI App',
    },
    tabBar: config.tabBar,
    subpackages: config.subpackages,
  }, null, 2)
}

export function generateProjectConfig(): string {
  return JSON.stringify({
    miniprogramRoot: './',
    projectname: 'xui-mini-app',
    description: 'XUI Mini Program',
    appid: '',
    setting: {
      urlCheck: false,
      es6: true,
      postcss: true,
      minified: true,
    },
    compileType: 'miniprogram',
  }, null, 2)
}

export function processVueFile(source: string, unitRatio: number): {
  wxml: string
  wxss: string[]
  js: string
  json: MiniPageConfig
} {
  const { template, script, styles } = transformSFC({
    source,
    target: 'mini',
    unitRatio,
  })

  const pageConfig: MiniPageConfig = {
    usingComponents: {},
  }

  const wxssContent = styles.length > 0
    ? styles.map((s, i) => `.wxss${i > 0 ? i : ''}{\n${s}\n}`).join('\n')
    : ''

  return {
    wxml: template,
    wxss: [wxssContent],
    js: script || generatePageJs('page'),
    json: pageConfig,
  }
}
